spring.application.name=movie

# =========================
# 서버 설정
# =========================

server.port=8080
server.address=0.0.0.0


# =========================
# MySQL DB
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/movie_db

spring.datasource.username=root

spring.datasource.password=1234


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# =========================
# TMDB API
# =========================

tmdb.api.key=005f181dd5057bff5a7f9827147574fa

tmdb.api.base-url=https://api.themoviedb.org/3